CREATE TABLE Categories (
    Id INT IDENTITY PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL,
    Slug NVARCHAR(160) NOT NULL UNIQUE,
    Description NVARCHAR(1000) NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    ModifiedDate DATETIME2 NULL,
    CreatedBy NVARCHAR(450) NULL,
    ModifiedBy NVARCHAR(450) NULL,
    IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE Products (
    Id INT IDENTITY PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    Slug NVARCHAR(220) NOT NULL UNIQUE,
    Description NVARCHAR(MAX) NULL,
    Price DECIMAL(18,2) NOT NULL,
    StockQuantity INT NOT NULL,
    ImageUrl NVARCHAR(500) NULL,
    IsFeatured BIT NOT NULL DEFAULT 0,
    CategoryId INT NOT NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    ModifiedDate DATETIME2 NULL,
    CreatedBy NVARCHAR(450) NULL,
    ModifiedBy NVARCHAR(450) NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_Products_Categories FOREIGN KEY (CategoryId) REFERENCES Categories(Id)
);

CREATE TABLE Orders (
    Id INT IDENTITY PRIMARY KEY,
    UserId NVARCHAR(450) NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    Status NVARCHAR(50) NOT NULL,
    ShippingAddress NVARCHAR(1000) NOT NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    ModifiedDate DATETIME2 NULL,
    CreatedBy NVARCHAR(450) NULL,
    ModifiedBy NVARCHAR(450) NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_Orders_AspNetUsers FOREIGN KEY (UserId) REFERENCES AspNetUsers(Id)
);

CREATE TABLE OrderItems (
    Id INT IDENTITY PRIMARY KEY,
    OrderId INT NOT NULL,
    ProductId INT NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    ModifiedDate DATETIME2 NULL,
    CreatedBy NVARCHAR(450) NULL,
    ModifiedBy NVARCHAR(450) NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_OrderItems_Orders FOREIGN KEY (OrderId) REFERENCES Orders(Id),
    CONSTRAINT FK_OrderItems_Products FOREIGN KEY (ProductId) REFERENCES Products(Id)
);

CREATE TABLE SiteContents (
    Id INT IDENTITY PRIMARY KEY,
    [Key] NVARCHAR(100) NOT NULL,
    [Value] NVARCHAR(MAX) NOT NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    ModifiedDate DATETIME2 NULL,
    CreatedBy NVARCHAR(450) NULL,
    ModifiedBy NVARCHAR(450) NULL,
    IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE Testimonials (
    Id INT IDENTITY PRIMARY KEY,
    CustomerName NVARCHAR(120) NOT NULL,
    City NVARCHAR(120) NOT NULL,
    ReviewText NVARCHAR(1200) NOT NULL,
    Rating INT NOT NULL,
    DisplayOrder INT NOT NULL DEFAULT 0,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    ModifiedDate DATETIME2 NULL,
    CreatedBy NVARCHAR(450) NULL,
    ModifiedBy NVARCHAR(450) NULL,
    IsDeleted BIT NOT NULL DEFAULT 0
);
